// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjO71PsLOmMDo7OZT9w3c3nY5yikQIBCc',
    appId: '1:1069539956036:web:c5c5274a2c8b70cbc67311',
    messagingSenderId: '1069539956036',
    projectId: 'catchmflixxapp',
    authDomain: 'catchmflixxapp.firebaseapp.com',
    storageBucket: 'catchmflixxapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcG4Ox_Q7d6e3hNR2aacy6K2Wtl_z9Rfw',
    appId: '1:1069539956036:android:7a87bdd547b18301c67311',
    messagingSenderId: '1069539956036',
    projectId: 'catchmflixxapp',
    storageBucket: 'catchmflixxapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxuf-TTf1UU52IWoKO6D2o7KJY3IB2bo',
    appId: '1:1069539956036:ios:4a243313c0841547c67311',
    messagingSenderId: '1069539956036',
    projectId: 'catchmflixxapp',
    storageBucket: 'catchmflixxapp.appspot.com',
    iosBundleId: 'com.catchmflixx.catchmflixxapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxuf-TTf1UU52IWoKO6D2o7KJY3IB2bo',
    appId: '1:1069539956036:ios:4a243313c0841547c67311',
    messagingSenderId: '1069539956036',
    projectId: 'catchmflixxapp',
    storageBucket: 'catchmflixxapp.appspot.com',
    iosBundleId: 'com.catchmflixx.catchmflixxapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjO71PsLOmMDo7OZT9w3c3nY5yikQIBCc',
    appId: '1:1069539956036:web:4827bb7b07087ac8c67311',
    messagingSenderId: '1069539956036',
    projectId: 'catchmflixxapp',
    authDomain: 'catchmflixxapp.firebaseapp.com',
    storageBucket: 'catchmflixxapp.appspot.com',
  );
}
